# Clase Nro. 6: Álgebra Lineal

> El álgebra lineal es una rama de las matemáticas que estudia conceptos tales como vectores, matrices, espacio dual, sistemas de ecuaciones lineales y en su enfoque de manera más formal, espacios vectoriales y sus transformaciones lineales

np.linalg: paquete de álgebra lineal en NumPy 

- Funciones básicas 
    - vectores
    - operaciones con vectores 
    - norma de un vector
    - operaciones con matrices
    - inversa de una matriz
    - determinante
- Resolución de sistemas


In [ ]:
!pip install numpy

In [1]:
import numpy as np

_Con el manejo básico de arrays en Python con NumPy, es hora de pasar a operaciones más interesantes como son las propias del Álgebra Lineal._

_Los productos escalares y las inversiones de matrices están por todas partes en los programas científicos e ingenieriles, así que vamos a estudiar cómo se realizan en Python._

Como sabemos, las operaciones del álgebra lineal aparecen con mucha frecuencia a la hora de resolver sistemas de ecuaciones en derivadas parciales y en general al linealizar problemas de todo tipo, y suele ser necesario resolver sistemas con un número enorme de ecuaciones e incógnitas. Gracias a los arrays de NumPy podemos abordar este tipo de cálculos en Python, ya que todas las funciones están escritas en C o Fortran y tenemos la opción de usar bibliotecas optimizadas al límite.

El paquete de álgebra lineal en NumPy se llama `linalg`, así que importando NumPy con la convención habitual podemos acceder a él escribiendo `np.linalg`. 

**Pero ¿Porqué álgebra lineal?** 

Si entendemos álgebra lineal podremos desarrollar una mejor intuición para el aprendizaje automático y algoritmos. Además, también seremos capaces de desarrollar algoritmos desde cero y hacer variaciones de ellos.

**¿Qué es un vector?**

Un vector tiene tanto magnitud como dirección. Utilizamos vectores para describir, por ejemplo, la velocidad de objetos en movimiento.

Por dirección, se refiere a dónde en el espacio apunta la “flecha”, y la magnitud te dice qué tan lejos debes ir en esa dirección. Si solo tienes magnitud, pero no dirección, entonces estás hablando de escalares. Una vez que le das al escalar alguna dirección, se convierte en un vector.

Un vector se representa con una letra minúscula y una flecha arriba, apuntando a la derecha

![vector](https://cdn-images-1.medium.com/max/800/1*6dAzelg6O36hbb74L7b1gQ.png)

In [2]:
np.array([3, 2])

array([3, 2])

**Suma de vectores**

Para sumar los vectores (x₁,y₁) y (x₂,y₂), sumamos los componentes correspondientes de cada vector: (x₁+x₂,y₁+y₂)

![suma de vectores](https://cdn-images-1.medium.com/max/800/0*9r4Qmivh-MSPFqM3.png)

In [3]:
a = np.array([6, -2])
b = np.array([-4, 4])
print(a+b)

[2 2]


**Multiplicar un vector por un escalar**

![](https://cdn-images-1.medium.com/max/800/0*YNlBN98aoAyV4DAL.png)

In [4]:
a = np.array([2, 1])
print(3 * a)

[6 3]


**Producto punto o escalar**

Esto suena raro, pero no es más que la multiplicación de vectores cuyo resultado es un escalar. Para calcular el producto escalar de dos vectores, primero debemos multiplicar los elementos correspondientes y luego sumar los términos del producto.

En la siguiente fórmula lo vemos mucho más fácil

![image.png](https://cdn-images-1.medium.com/max/800/0*lMEmcY_nXD4LOvHD.png)

<img src="https://cdn-images-1.medium.com/max/800/1*ys1bMjlrtchr_ClPah7Z2w.png" alt="drawing" width="500"/>

In [5]:
a = np.array([3, 2])
b = np.array([2, 2])
print(a.dot(b))

10


**Norma vectorial**

La norma es solo otro término para la magnitud de un vector y se denota con dos lineas dobles (||) en cada lado. Se define como una raíz cuadrada de la suma de cuadrados para cada componente de un vector

Pasos: 
- Elevar al cuadrado cada componente
- Suma todos los cuadrados
- Toma la raíz cuadrada

Trabajemos ahora con la formula:

![](https://cdn-images-1.medium.com/max/800/0*fIYtRzCI6vI8THet.png)

<img src="https://cdn-images-1.medium.com/max/800/1*95bAtiMefunHPhLbwOYnnQ.png" alt="drawing" width="500"/>

In [6]:
a = np.array([3, 2, 6])
print(np.linalg.norm(a))

7.0


**Vector unitario**

Los vectores unitarios son aquellos cuya magnitud es exactamente 1 unidad. Son muy útiles por diversas razones. Específicamente, los vectores unitarios [0,1] y [1,0] juntos pueden formar cualquier otro vector.

Un vector unitario se denota con mayor frecuencia con un símbolo de sombrero (^) y se determina calculando la norma y luego dividiendo cada componente del vector con la norma.

Suena complejo, pero vamos a hacer un ejercicio para poder ver que es más complejo de lo que imaginamos

![](https://cdn-images-1.medium.com/max/800/0*3Qkk3weTeyaMYthE.png)

<img src="https://cdn-images-1.medium.com/max/800/1*wFFS0a3soJRC7XlZxzJ6Kg.png" alt="drawing" width="400" height="400"/>

In [8]:
def unit_vector(a):
    return a/np.linalg.norm(a)

u = np.array([3, 6, 4])
print(unit_vector(u))

[0.38411064 0.76822128 0.51214752]


## Operaciones con matrices

 ¿Qué es una matriz? Una matriz es simplemente un arreglo rectangular de números
 
En data science las usamos un montón, así no nos demos cuenta. Es muy importante de diferenciar un vector de una matriz. En pocas palabras un vector es una sola columna (atributo) en su conjunto de datos y una matriz es una colección de todas las columnas

**Definición de matrices**

$A = \begin{equation}
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
\end{bmatrix}
\end{equation}$

In [10]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

$B = \begin{equation}
\begin{bmatrix}
5 & 5 & 5\\
5 & 5 & 5\\
\end{bmatrix}
\end{equation}$

In [13]:
B = np.full((2, 3), 5)
B

array([[5, 5, 5],
       [5, 5, 5]])

$v = \begin{equation}
\begin{bmatrix}
6\\
7\\
8
\end{bmatrix}
\end{equation}$

In [18]:
v = np.array([6, 7, 8]).reshape(3, 1)
v

array([[6],
       [7],
       [8]])

**Suma de matrices**

![](https://cdn-images-1.medium.com/max/1600/0*eKgiNEikBO09MCN1.png)

In [19]:
A + B

array([[ 6,  7,  8],
       [ 9, 10, 11]])

**Resta de matrices**

In [20]:
A -B

array([[-4, -3, -2],
       [-1,  0,  1]])

**Multiplicación por un escalar**

![](https://cdn-images-1.medium.com/max/1600/0*RMuq3SZ_8Z4KE-48.png)

$C = \begin{equation}
\begin{bmatrix}
3 & 5\\
2 & 0\\
\end{bmatrix}
\end{equation}$

In [21]:
C = np.array([[3, 5], [2, 0]])
print(2 * C)

[[ 6 10]
 [ 4  0]]


**Matriz transpuesta**

![](https://cdn-images-1.medium.com/max/1600/0*mrjFrMfmMcj4xsUe.png)

$D = \begin{equation}
\begin{bmatrix}
3 & 4\\
1 & 0\\
\end{bmatrix}
\end{equation}$

In [22]:
D = np.array([[3, 4], [1, 0]])
print(D.T)

[[3 1]
 [4 0]]


**Matriz identidad**

In [24]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
#help(np.linalg)

Recordemos que si queremos usar una función de un paquete pero no queremos escribir la "ruta" completa cada vez, podemos usar la sintaxis `from package import func`:

In [ ]:
from numpy.linalg import norm, det
norm

El producto matricial usual (no el que se hace elemento a elemento, sino el del álgebra lineal) se calcula con la misma función que el producto matriz-vector y el producto escalar vector-vector: con la función `dot`, que **no** está en el paquete `linalg` sino directamente en `numpy` y no hace falta importarlo.

In [ ]:
np.dot

Una consideración importante a tener en cuenta es que en NumPy no hace falta ser estricto a la hora de manejar vectores como si fueran matrices columna, siempre que la operación sea consistente. Un vector es una matriz con una sola dimensión: por eso si calculamos su traspuesta no funciona.

In [27]:
M = np.array([
    [1, 2],
    [3, 4]
])
v = np.array([1, -1])

v

In [28]:
M.T

array([[1, 3],
       [2, 4]])

In [29]:
v

array([ 1, -1])

In [30]:
v.T

array([ 1, -1])

In [31]:
v.shape

(2,)

In [32]:
v.reshape(2,1)

array([[ 1],
       [-1]])

In [33]:
v.reshape(2,1).T

array([[ 1, -1]])

In [34]:
u = np.dot(M, v)
u

array([-1, -1])

**Multiplicación entre matrices**

In [35]:
A = np.array([[3, 2], [1, 3]])
B = np.array([[2, 2], [1, 2]])

In [36]:
A.shape

(2, 2)

In [37]:
B.shape

(2, 2)

In [39]:
print(A)
print(B)

[[3 2]
 [1 3]]
[[2 2]
 [1 2]]


In [40]:
# producto matricial
np.dot(A, B)

array([[ 8, 10],
       [ 5,  8]])

Ejemplo

Resolver el producto de matrices del siguiente [vídeo](https://www.youtube.com/watch?v=Tjrm3HsqBXE&ab_channel=Matem%C3%A1ticasprofeAlex)

In [41]:
A = np.array([[5, 3, -4, -2], [8, -1, 0, -3]])
B = np.array([[1, 4, 0], [-5, 3, 7], [0, -9, 5], [5, 1, 4]])
np.dot(A, B)

array([[-20,  63,  -7],
       [ -2,  26, -19]])


**Determinante de una matriz**

In [42]:
# calcula el determinante de una matriz
A = np.array([[3, 2], [1, 3]])
np.linalg.det(A)

7.000000000000001

**Inversa de una matriz**

Para calcular la matriz inversa en Python, use la función linalg.inv () del módulo numpy.

linalg.inv(x) 

El parámetro x de la función es una **matriz cuadrada** invertible M definida con la función array() de numpy. 

La función genera la matriz inversa M-1 de la matriz M.

> ¿Qué es la matriz inversa? La matriz inversa M-1 de una matriz cuadrada es una matriz tal que el producto M · M-1 es igual a una matriz de identidad I.



<img src="http://how.okpedia.org/data/okpediaorg/matrix-inverse-identity-formula.gif" alt="drawing" />


Encuentre la matriz inversa M-1 de la siguiente matriz invertible M.

![](http://how.okpedia.org/data/okpediaorg/matrix-inverse-example-python-1.gif)

In [44]:
M=np.array([[3,4,-1],[2,0,1],[1,3,-2]])

In [45]:
# Calcula la matriz inversa con la función linalg.inv().
Minv = np.linalg.inv(M)
Minv

array([[-0.6,  1. ,  0.8],
       [ 1. , -1. , -1. ],
       [ 1.2, -1. , -1.6]])

La matriz de salida inversa es también un objeto array(). Se puede leer como una lista anidada. Los elementos de la matriz inversa son números reales.

![](http://how.okpedia.org/data/okpediaorg/matrix-inverse-example-9.gif)

Verificación. El producto de la matriz M para la matriz M-1 es una matriz de identidad.


![](http://how.okpedia.org/data/okpediaorg/matrix-inverse-example-10.gif)

In [47]:
# verificación
Mident = np.round(np.dot(M, Minv))
print(Mident)

[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


**Otro ejemplo** 
Encontrar el determinante y la matriz inversa de D.

$ D = \begin{equation}
\begin{bmatrix}
1 & 2\\
3 & 4\\
\end{bmatrix}
\end{equation}$


In [48]:
D = np.array([[1, 2], [3, 4]])
D

array([[1, 2],
       [3, 4]])

In [49]:
# cálculo del determinante de la matriz D
np.linalg.det(D)

-2.0000000000000004

In [50]:
# y la matriz inversa de D
np.linalg.inv(D)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

**Solución de ecuaciones con matrices**

1. Resolver el siguiente sistema de ecuaciones

$\begin{eqnarray}
3x + y  = 9 \\
x + 2y = 8 \\
\end{eqnarray}$

In [51]:
M = np.array([[3, 1], [1, 2]])
coef = np.array([9, 8])

x = np.linalg.solve(M, coef)
x

array([2., 3.])

### Ejercicios

1- Hallar el producto de estas dos matrices y su determinante:

$$\begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 1 \\ -1 & 0 & 1 \end{pmatrix} \begin{pmatrix} 2 & 3 & -1 \\ 0 & -2 & 1 \\ 0 & 0 & 3 \end{pmatrix}$$

In [58]:
from numpy.linalg import det

In [55]:
A = np.array([
    [1, 0, 0],
    [2, 1, 1],
    [-1, 0, 1]
])
print(A)

[[ 1  0  0]
 [ 2  1  1]
 [-1  0  1]]


In [56]:
B = np.array([
    [2, 3, -1],
    [0, -2, 1],
    [0, 0, 3]
])

print(B)

[[ 2  3 -1]
 [ 0 -2  1]
 [ 0  0  3]]


In [57]:
C = np.dot(A, B)
C

array([[ 2,  3, -1],
       [ 4,  4,  2],
       [-2, -3,  4]])

In [59]:
det(C)

-12.0

3- Resuelva el siguiente sistema de ecuaciones

$\begin{eqnarray}
x + 2y  = 3 \\
3x + 4y = 5 \\
\end{eqnarray}$

In [60]:
M = np.array([[1, 2], [3, 4]])
coef = np.array([3, 5])
sol = np.linalg.solve(M, coef)
print(sol)

[-1.  2.]


4- Un ingeniero escribe dos ecuaciones que describen el circuito, como sigue: 

$\begin{gather}
300I_{1} + 500(I_{1}-I_{2})-20 = 0\\
200I_{2} + 500(I_{2}-I_{1}) +10 = 0\\
\end{gather}$

![circuito](./img/problem4.png)


Coloque las dos ecuaciones en forma estándar y resuelva las dos ecuaciones:

```
300 I1 + 500 I1 - 500 I2 = 20 -> 800 I1 - 500 I2 = 20
                                -500 I1 + 700 I2 = -10
```

In [62]:
M = np.array([[800, -500], [-500, 700]])
coef = np.array([20, -10])
sol = np.linalg.solve(M, coef)
print(sol)

[0.02903226 0.00645161]


5- Resolver el siguiente sistema de ecuaciones

![](./img/problem5.png)

In [63]:
np.round?

Signature: np.round(a, decimals=0, out=None)
Docstring:
Round an array to the given number of decimals.

See Also
--------
around : equivalent function; see for details.
File:      d:\jupyter\env\lib\site-packages\numpy\core\fromnumeric.py
Type:      function


3- Resolver el siguiente sistema:

$$ \begin{pmatrix} 2 & 0 & 0 \\ -1 & 1 & 0 \\ 3 & 2 & -1 \end{pmatrix} \begin{pmatrix} 1 & 1 & 1 \\ 0 & 1 & 2 \\ 0 & 0 & 1 \end{pmatrix} \begin{pmatrix} x \\ y \\ z \end{pmatrix} = \begin{pmatrix} -1 \\ 3 \\ 0 \end{pmatrix} $$

In [64]:
M = np.dot(
np.array([
    [2, 0, 0],
    [-1, 1, 0],
    [3, 2, -1]
]),
np.array([
    [1, 1, 1],
    [0, 1, 2],
    [0, 0, 1]
]))
M

array([[ 2,  2,  2],
       [-1,  0,  1],
       [ 3,  5,  6]])

In [66]:
x = np.linalg.solve(M, np.array([-1, 3, 0]))
x

array([ 0.5, -4.5,  3.5])