<a href="https://colab.research.google.com/github/lsantiago/PythonIntermedio/blob/master/Clases/Semana6_ALGEBRA/algebra_lineal_apuntes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase Nro. 6: Álgebra Lineal

> El álgebra lineal es una rama de las matemáticas que estudia conceptos tales como vectores, matrices, espacio dual, sistemas de ecuaciones lineales y en su enfoque de manera más formal, espacios vectoriales y sus transformaciones lineales

np.linalg: paquete de álgebra lineal en NumPy 

- Funciones básicas 
    - vectores
    - operaciones con vectores 
    - norma de un vector
    - operaciones con matrices
    - inversa de una matriz
    - determinante
- Resolución de sistemas


_Con el manejo básico de arrays en Python con NumPy, es hora de pasar a operaciones más interesantes como son las propias del Álgebra Lineal._

_Los productos escalares y las inversiones de matrices están por todas partes en los programas científicos e ingenieriles, así que vamos a estudiar cómo se realizan en Python._

Como sabemos, las operaciones del álgebra lineal aparecen con mucha frecuencia a la hora de resolver sistemas de ecuaciones en derivadas parciales y en general al linealizar problemas de todo tipo, y suele ser necesario resolver sistemas con un número enorme de ecuaciones e incógnitas. Gracias a los arrays de NumPy podemos abordar este tipo de cálculos en Python, ya que todas las funciones están escritas en C o Fortran y tenemos la opción de usar bibliotecas optimizadas al límite.

El paquete de álgebra lineal en NumPy se llama `linalg`, así que importando NumPy con la convención habitual podemos acceder a él escribiendo `np.linalg`. 

**Pero ¿Porqué álgebra lineal?** 

Si entendemos álgebra lineal podremos desarrollar una mejor intuición para el aprendizaje automático y algoritmos. Además, también seremos capaces de desarrollar algoritmos desde cero y hacer variaciones de ellos.

**¿Qué es un vector?**

Un vector tiene tanto magnitud como dirección. Utilizamos vectores para describir, por ejemplo, la velocidad de objetos en movimiento.

Por dirección, se refiere a dónde en el espacio apunta la “flecha”, y la magnitud te dice qué tan lejos debes ir en esa dirección. Si solo tienes magnitud, pero no dirección, entonces estás hablando de escalares. Una vez que le das al escalar alguna dirección, se convierte en un vector.

Un vector se representa con una letra minúscula y una flecha arriba, apuntando a la derecha

![vector](https://cdn-images-1.medium.com/max/800/1*6dAzelg6O36hbb74L7b1gQ.png)

**Suma de vectores**

Para sumar los vectores (x₁,y₁) y (x₂,y₂), sumamos los componentes correspondientes de cada vector: (x₁+x₂,y₁+y₂)

![suma de vectores](https://cdn-images-1.medium.com/max/800/0*9r4Qmivh-MSPFqM3.png)

In [2]:
import numpy as np

**Multiplicar un vector por un escalar**

![](https://cdn-images-1.medium.com/max/800/0*YNlBN98aoAyV4DAL.png)

**Producto punto o escalar**

Esto suena raro, pero no es más que la multiplicación de vectores cuyo resultado es un escalar. Para calcular el producto escalar de dos vectores, primero debemos multiplicar los elementos correspondientes y luego sumar los términos del producto.

En la siguiente fórmula lo vemos mucho más fácil

![image.png](https://cdn-images-1.medium.com/max/800/0*lMEmcY_nXD4LOvHD.png)

<img src="https://cdn-images-1.medium.com/max/800/1*ys1bMjlrtchr_ClPah7Z2w.png" alt="drawing" width="500"/>

**Norma vectorial**

La norma es solo otro término para la magnitud de un vector y se denota con dos lineas dobles (||) en cada lado. Se define como una raíz cuadrada de la suma de cuadrados para cada componente de un vector

Pasos: 
- Elevar al cuadrado cada componente
- Suma todos los cuadrados
- Toma la raíz cuadrada

Trabajemos ahora con la formula:

![](https://cdn-images-1.medium.com/max/800/0*fIYtRzCI6vI8THet.png)

<img src="https://cdn-images-1.medium.com/max/800/1*95bAtiMefunHPhLbwOYnnQ.png" alt="drawing" width="500"/>

In [3]:
a = np.array([3,2,6])
print (np.linalg.norm(a))

7.0


**Vector unitario**

Los vectores unitarios son aquellos cuya magnitud es exactamente 1 unidad. Son muy útiles por diversas razones. Específicamente, los vectores unitarios [0,1] y [1,0] juntos pueden formar cualquier otro vector.

Un vector unitario se denota con mayor frecuencia con un símbolo de sombrero (^) y se determina calculando la norma y luego dividiendo cada componente del vector con la norma.

Suena complejo, pero vamos a hacer un ejercicio para poder ver que es más complejo de lo que imaginamos

![](https://cdn-images-1.medium.com/max/800/0*3Qkk3weTeyaMYthE.png)

<img src="https://cdn-images-1.medium.com/max/800/1*wFFS0a3soJRC7XlZxzJ6Kg.png" alt="drawing" width="400" height="400"/>

In [4]:
def unit_vertor(a):
    return a/np.linalg.norm(a)

u = np.array([3,6,4])
print (unit_vertor(u))

[0.38411064 0.76822128 0.51214752]


## Operaciones con matrices

 ¿Qué es una matriz? Una matriz es simplemente un arreglo rectangular de números
 
En data science las usamos un montón, así no nos demos cuenta. Es muy importante de diferenciar un vector de una matriz. En pocas palabras un vector es una sola columna (atributo) en su conjunto de datos y una matriz es una colección de todas las columnas

**Definición de matrices**

$A = \begin{equation}
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
\end{bmatrix}
\end{equation}$

In [5]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

$B = \begin{equation}
\begin{bmatrix}
5 & 5 & 5\\
5 & 5 & 5\\
\end{bmatrix}
\end{equation}$

In [10]:
#b = np.array([[5,5,5],[5,5,5]]) # esta definicion cuando tenemos una matriz con los mismos datos podemos hacrlo de la siguiente maenra
b = np.full((2,3), 5) # aqui le mandos una matrsi de 2 filas por 3 columnas y llene con 5
b

array([[5, 5, 5],
       [5, 5, 5]])

$v = \begin{equation}
\begin{bmatrix}
6\\
7\\
8
\end{bmatrix}
\end{equation}$

In [9]:
v = np.array([6,7,8]).reshape(3,1)
v

array([[6],
       [7],
       [8]])

**Suma de matrices**

![](https://cdn-images-1.medium.com/max/1600/0*eKgiNEikBO09MCN1.png)

In [11]:
a + b 

array([[ 6,  7,  8],
       [ 9, 10, 11]])

**Resta de matrices**

In [12]:
a - b

array([[-4, -3, -2],
       [-1,  0,  1]])

**Multiplicación por un escalar**

![](https://cdn-images-1.medium.com/max/1600/0*RMuq3SZ_8Z4KE-48.png)

\begin{equation}
\begin{bmatrix}
6 & 8 & 1\\
2 & 9 & 3\\
4 & 5 & 1
\end{bmatrix}
\end{equation}

In [15]:
c = np.array([[3,5],[2,0]])
c

array([[3, 5],
       [2, 0]])

**Matriz transpuesta**

![](https://cdn-images-1.medium.com/max/1600/0*mrjFrMfmMcj4xsUe.png)

In [17]:
d= np.array([[3,4],[1,0]])
print (d.T) #agregamos T para la transpuesta

[[3 1]
 [4 0]]


**Matriz identidad**

In [19]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#help(np.linalg)

Recordemos que si queremos usar una función de un paquete pero no queremos escribir la "ruta" completa cada vez, podemos usar la sintaxis `from package import func`:

In [20]:
from numpy.linalg import norm, det
norm

<function numpy.linalg.norm(x, ord=None, axis=None, keepdims=False)>

El producto matricial usual (no el que se hace elemento a elemento, sino el del álgebra lineal) se calcula con la misma función que el producto matriz-vector y el producto escalar vector-vector: con la función `dot`, que **no** está en el paquete `linalg` sino directamente en `numpy` y no hace falta importarlo.

In [ ]:
np.dot

Una consideración importante a tener en cuenta es que en NumPy no hace falta ser estricto a la hora de manejar vectores como si fueran matrices columna, siempre que la operación sea consistente. Un vector es una matriz con una sola dimensión: por eso si calculamos su traspuesta no funciona.

In [21]:
M = np.array([
    [1, 2],
    [3, 4]
])
v = np.array([1, -1])

v

In [22]:
M.T

array([[1, 3],
       [2, 4]])

In [25]:
v.T # transpuesta

array([ 1, -1])

In [26]:
v.reshape(2,1).T

array([[ 1, -1]])

In [27]:
u = np.dot(M, v)  #producto  escalar
u

array([-1, -1])

**Multiplicación entre matrices**

In [28]:
a= np.array([[3,2],[4,5]])
b= np.array([[3,2],[4,5]])
#para saber las dinesio de una matriz n*m ?
a.shape

(2, 2)

In [32]:
# # columnas 1 matriz = 2 filas matriz 2
a

array([[3, 2],
       [4, 5]])

In [31]:
# producto matriciala
np.dot(a,b)

array([[17, 16],
       [32, 33]])

In [34]:
# PARA PODER MULTIPLAR UNA MATRIZ

# # columnas 1 matriz = 2 filas matriz 2

a= np.array([[5,3,-4,-2],[8,-1,0,-3]])
b= np.array([[1,4,0],[-5,3,7],[0,-9,5],[5,1,4]])
np.dot(a,b)

array([[-20,  63,  -7],
       [ -2,  26, -19]])


**Determinante de una matriz**

In [37]:
# calcula el determinante de una matriz
determiante= np.array([[3,2],[4,5]])
np.linalg.det(determiante) 

6.999999999999999

**Inversa de una matriz**

Para calcular la matriz inversa en Python, use la función linalg.inv () del módulo numpy.

linalg.inv(x) 

El parámetro x de la función es una matriz cuadrada invertible M definida con la función array() de numpy. 

La función genera la matriz inversa M-1 de la matriz M.

> ¿Qué es la matriz inversa? La matriz inversa M-1 de una matriz cuadrada es una matriz tal que el producto M · M-1 es igual a una matriz de identidad I.



<img src="http://how.okpedia.org/data/okpediaorg/matrix-inverse-identity-formula.gif" alt="drawing" />


Encuentre la matriz inversa M-1 de la siguiente matriz invertible M.

![](http://how.okpedia.org/data/okpediaorg/matrix-inverse-example-python-1.gif)

In [39]:
m=np.array([[3,4,-1],[2,0,1],[1,3,-2]])
m

array([[ 3,  4, -1],
       [ 2,  0,  1],
       [ 1,  3, -2]])

In [41]:
# Calcula la matriz inversa con la función linalg.inv().
mInversa=np.linalg.inv(m)
mInversa

array([[-0.6,  1. ,  0.8],
       [ 1. , -1. , -1. ],
       [ 1.2, -1. , -1.6]])

La matriz de salida inversa es también un objeto array(). Se puede leer como una lista anidada. Los elementos de la matriz inversa son números reales.

![](http://how.okpedia.org/data/okpediaorg/matrix-inverse-example-9.gif)

Verificación. El producto de la matriz M para la matriz M-1 es una matriz de identidad.


![](http://how.okpedia.org/data/okpediaorg/matrix-inverse-example-10.gif)

In [45]:
# verificación
mIdentidad = np.round(np.dot(m,mInversa)) #np.round = redondear decimales
mIdentidad

array([[ 1., -0., -0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

**Otro ejemplo** 
Encontrar el determinante y la matriz inversa de D.

$ D = \begin{equation}
\begin{bmatrix}
1 & 2\\
3 & 4\\
\end{bmatrix}
\end{equation}$


In [55]:
D = np.array([[1, 2], [3, 4]])
determiante=np.linalg.det(D)  #detemiante
mInversa=np.linalg.inv(D) # inversa

In [56]:
# cálculo del determinante
print(round(determiante))

-2


In [57]:
# y el inverso
print(mInversa) 

[[-2.   1. ]
 [ 1.5 -0.5]]


**Solución de ecuaciones con matrices**

1. Resolver el siguiente sistema de ecuaciones

$\begin{eqnarray}
3x + y  = 9 \\
x + 2y = 8 \\
\end{eqnarray}$

In [60]:
izq = np.array([[3,1],[1,2]]) # amtriz solo con los primera parte antes del  = 
der = np.array([9,8]) # matriz despues del =

resultado = np.linalg.solve (izq,der)
resultado

array([2., 3.])

### Ejercicios

1- Hallar el producto de estas dos matrices y su determinante:

$$\begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 1 \\ -1 & 0 & 1 \end{pmatrix} \begin{pmatrix} 2 & 3 & -1 \\ 0 & -2 & 1 \\ 0 & 0 & 3 \end{pmatrix}$$

In [61]:
from numpy.linalg import det

In [62]:
a = np.array ([
            [1,0,0],
            [2,1,1],
            [-1,0,1]
            ])
b = np.array ([
            [2,3,-1],
            [0,-2,1],
            [0,0,3]
            ])



In [63]:
print (a)
print (b)

[[ 1  0  0]
 [ 2  1  1]
 [-1  0  1]]
[[ 2  3 -1]
 [ 0 -2  1]
 [ 0  0  3]]


In [67]:
 #produto de nuestras dos matrices
c=np.dot(a,b)
c

array([[ 2,  3, -1],
       [ 4,  4,  2],
       [-2, -3,  4]])

In [69]:
#determiante
np.linalg.det(c) #opcion 1
det(c) #opcion 2


-12.0

3- Resuelva el siguiente sistema de ecuaciones

$\begin{eqnarray}
x + 2y  = 3 \\
3x + 4y = 5 \\
\end{eqnarray}$

In [79]:
left = np.array([[1,2],[3,4]]) # amtriz solo con los primera parte antes del  = 
rigth = np.array([3,5]) # matriz despues del =
resultado = np.linalg.solve (left,rigth)
resultado


array([-1.,  2.])

4- Un ingeniereo escribe dos ecuaciones que describen el circuito, como sigue: 

$\begin{gather}
300I_{1} + 500(I_{1}-I_{2})-20 = 0\\
200I_{2} + 500(I_{2}-I_{1}) +10 = 0\\
\end{gather}$

![circuito](https://github.com/lsantiago/PythonIntermedio/blob/master/Clases/Semana6_ALGEBRA/img/problem4.png?raw=1)

Coloque las dos ecuaciones en forma estándar y resuelva las dos ecuaciones:

In [81]:
left = np.array([[800,-500],[-500,700]]) # amtriz solo con los primera parte antes del  = 
rigth = np.array([20,-10]) # matriz despues del =
resultado = np.linalg.solve (left,rigth)
print (resultado)

[0.02903226 0.00645161]


5- Resolver el siguiente sistema de ecuaciones

![](https://github.com/lsantiago/PythonIntermedio/blob/master/Clases/Semana6_ALGEBRA/img/problem5.png?raw=1)

In [91]:
left = np.array([[6000,-2000,-4000],[-2000,15000,-5000],[-4000,-5000,12000]]) # amtriz solo con los primera parte antes del  = 
rigth = np.array([10,0,0]) # matriz despues del =
resultado = np.linalg.solve (left,rigth)
np.round(resultado, decimals=4)

array([0.0028, 0.0008, 0.0012])

3- Resolver el siguiente sistema:

$$ \begin{pmatrix} 2 & 0 & 0 \\ -1 & 1 & 0 \\ 3 & 2 & -1 \end{pmatrix} \begin{pmatrix} 1 & 1 & 1 \\ 0 & 1 & 2 \\ 0 & 0 & 1 \end{pmatrix} \begin{pmatrix} x \\ y \\ z \end{pmatrix} = \begin{pmatrix} -1 \\ 3 \\ 0 \end{pmatrix} $$

array([[ 2,  2,  2],
       [-1,  0,  1],
       [ 3,  5,  6]])

array([ 0.5, -4.5,  3.5])

True